# Generated by Django 5.0.6 on 2024-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosing', models.CharField(max_length=50, unique=True, verbose_name='Выбор')),
            ],
            options={
                'verbose_name': 'Добавить должность среди учащихся',
                'verbose_name_plural': 'Добавить должность среди учащихся',
            },
        ),
        migrations.CreateModel(
            name='NamesOfOlympia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosing', models.CharField(max_length=20, unique=True, verbose_name='Выбор')),
            ],
            options={
                'verbose_name': 'Добавить название олимпиады',
                'verbose_name_plural': 'Добавить названия олимпиад',
            },
        ),
        migrations.CreateModel(
            name='NameOfGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=10, verbose_name='Класс')),
                ('parallel', models.CharField(help_text='Например, А, Б, В и т.д.', max_length=1, verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'Добавить имени класса',
                'verbose_name_plural': 'Добавить имена классов',
                'unique_together': {('grade', 'parallel')},
            },
        ),
    ]
