# Generated by Django 5.0.6 on 2024-09-02 13:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confirmation_file',
            field=models.FileField(upload_to='checks/%Y/%m/%d/', validators=[users.models.validate_file_extension], verbose_name='Квитанция о переводе'),
        ),
    ]
