# Generated by Django 5.0.6 on 2024-07-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_donation_confirmeddonation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='money_check',
            new_name='confirmation_file',
        ),
    ]
