# Generated by Django 5.0.6 on 2024-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_money_check_donation_confirmation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confirmation_file',
            field=models.FileField(upload_to='', verbose_name='Фото чека'),
        ),
    ]
