# Generated by Django 5.0.6 on 2024-07-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_donation_confirmation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confirmation_file',
            field=models.FileField(upload_to='checks/%Y/%m/%d/', verbose_name='Фото чека'),
        ),
    ]
