# Generated by Django 5.0.6 on 2024-07-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_donation_confirmation_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmeddonation',
            options={'verbose_name': 'Подтвержденные переводы средств', 'verbose_name_plural': 'Подтвержденные переводы средств'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Не подтвержденные переводы средств', 'verbose_name_plural': 'Не подтвержденные переводы средств'},
        ),
    ]
