# Generated by Django 5.0.6 on 2024-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_confirmeddonation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmeddonation',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
