# Generated by Django 5.0.6 on 2024-07-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_confirmeddonation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confirmation_file',
            field=models.FileField(upload_to='checks/%Y/%m/%d/', verbose_name='Квитанция о переводе'),
        ),
    ]
