# Generated by Django 5.0.6 on 2024-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_donation_confirmation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
    ]
