services:
  - type: web
    name: gimnasium-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: sh -c "python manage.py migrate && python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='root').exists() or User.objects.create_superuser('root', 'root@example.com', 'root')\" && python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: REDIS_URL
        sync: false
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/tessdata
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1

  - type: worker
    name: gimnasium-celery
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A Gimnasium worker -l info
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: REDIS_URL
        sync: false
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/tessdata
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1