# Generated by Django 5.0.6 on 2024-07-07 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosing', models.CharField(max_length=50, unique=True, verbose_name='Выбор')),
            ],
            options={
                'verbose_name': 'Должности среди учащихся',
                'verbose_name_plural': 'Должности среди учащихся',
            },
        ),
        migrations.CreateModel(
            name='AppealToStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Обращение к ученикам',
                'verbose_name_plural': 'Обращение к ученикам',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер телефона(+996)')),
                ('address', models.CharField(max_length=200, null=True, unique=True, verbose_name='Адрес')),
                ('instagram', models.URLField(null=True, verbose_name='instagram')),
                ('youtube', models.URLField(null=True, verbose_name='Youtube')),
                ('telegram', models.URLField(null=True, verbose_name='telegram')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Выпускники',
                'verbose_name_plural': 'Выпускники',
            },
        ),
        migrations.CreateModel(
            name='NamesOfOlympia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosing', models.CharField(max_length=20, unique=True, verbose_name='Выбор')),
            ],
            options={
                'verbose_name': 'Название олимпиады',
                'verbose_name_plural': 'Название олимпиады',
            },
        ),
        migrations.CreateModel(
            name='OurAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('image', models.ImageField(upload_to='our_achievements/%Y/%m/%d/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наши достижения',
                'verbose_name_plural': 'Наши достижения',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('experience', models.CharField(choices=[('Год', '1'), ('От пяти лет', '5+'), ('От десяти лет', '10+')], max_length=50, verbose_name='Опыт')),
                ('subject', models.CharField(max_length=20, verbose_name='Предмет')),
                ('subject_ky', models.CharField(max_length=20, null=True, verbose_name='Предмет')),
                ('subject_ru', models.CharField(max_length=20, null=True, verbose_name='Предмет')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Образование')),
                ('education_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование')),
                ('education_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование')),
                ('successes', models.TextField(blank=True, verbose_name='Успехи')),
                ('successes_ky', models.TextField(blank=True, null=True, verbose_name='Успехи')),
                ('successes_ru', models.TextField(blank=True, null=True, verbose_name='Успехи')),
                ('image', models.ImageField(upload_to='teachers_images/%Y/%m/%d/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='ThanksNoteFromGraduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thanks_note_from_graduates_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Благодарственное письмо (от выпускников)',
                'verbose_name_plural': 'Благодарственное письмо (от выпускников)',
            },
        ),
        migrations.CreateModel(
            name='ThanksNoteFromStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thanks_note_from_students_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Благодарственное письмо (от учеников)',
                'verbose_name_plural': 'Благодарственное письмо (от учеников)',
            },
        ),
        migrations.CreateModel(
            name='NameOfGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('fifth', '5'), ('sixth', '6'), ('seventh', '7'), ('eighth', '8'), ('ninth', '9'), ('tenth', '10'), ('eleventh', '11')], max_length=10, verbose_name='Класс')),
                ('parallel', models.CharField(help_text='Например, А, Б, В и т.д.', max_length=1, verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'unique_together': {('grade', 'parallel')},
            },
        ),
        migrations.CreateModel(
            name='GimnasiumClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_grade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.nameofgrades', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('administrator_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.administratortypes', verbose_name='Позиция')),
                ('olympian_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпиец')),
                ('olympian_status_ky', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпиец')),
                ('olympian_status_ru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпиец')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gimnasiumclass', verbose_name='Класс')),
                ('classroom_teacher', models.ManyToManyField(to='main.teachers', verbose_name='Классный руководитель')),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='SchoolParliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.administratortypes', verbose_name='Должность')),
                ('student', models.ManyToManyField(blank=True, to='main.students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Парламент нашей гимназии',
                'verbose_name_plural': 'Парламент нашей гимназии',
            },
        ),
        migrations.CreateModel(
            name='Olympians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_olympia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.namesofolympia', verbose_name='Предмет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Олимпийцы',
                'verbose_name_plural': 'Олимпийцы',
            },
        ),
        migrations.AddField(
            model_name='gimnasiumclass',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.students', verbose_name='Ученик'),
        ),
        migrations.CreateModel(
            name='SuccessfulGraduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='successful_graduates/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.graduates', verbose_name='Выберите его(её) из списка')),
            ],
            options={
                'verbose_name': 'Успешные выпускники',
                'verbose_name_plural': 'Успешные выпускники',
            },
        ),
    ]
