# Generated by Django 5.0.6 on 2024-09-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduates',
            name='ort_ky',
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='ort_ru',
        ),
        migrations.RemoveField(
            model_name='olympians',
            name='name_of_olympia_ky',
        ),
        migrations.RemoveField(
            model_name='olympians',
            name='name_of_olympia_ru',
        ),
    ]
