# Generated by Django 5.0.6 on 2024-07-09 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='olympian_status_ky',
        ),
        migrations.RemoveField(
            model_name='students',
            name='olympian_status_ru',
        ),
        migrations.AlterField(
            model_name='graduates',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год'),
        ),
    ]
