# Generated by Django 5.0.6 on 2024-06-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_students_olympian_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='administrator_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.administratortypes'),
        ),
        migrations.AlterField(
            model_name='students',
            name='olympian_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia'),
        ),
    ]
