# Generated by Django 5.0.6 on 2024-07-09 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_students_olympian_status_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduates',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2024)], verbose_name='Год'),
        ),
    ]
