# Generated by Django 5.0.6 on 2024-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_graduates_ort_ky_remove_graduates_ort_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='title_ky',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='title_ky',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
