# Generated by Django 5.0.6 on 2024-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gallery_images_alter_graduates_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
