# Generated by Django 5.0.6 on 2024-07-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_students_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gimnasiumclass',
            options={'verbose_name': 'Классы Гимназии №3', 'verbose_name_plural': 'Классы Гимназии №3'},
        ),
        migrations.AlterField(
            model_name='nameofgrades',
            name='grade',
            field=models.CharField(choices=[('5', 'fifth'), ('6', 'sixth'), ('7', 'seventh'), ('8', 'eighth'), ('9', 'ninth'), ('10', 'tenth'), ('11', 'eleventh')], max_length=10, verbose_name='Класс'),
        ),
    ]
