# Generated by Django 5.0.6 on 2024-07-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gimnasiumclass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameofgrades',
            name='grade',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=10, verbose_name='Класс'),
        ),
    ]
