# Generated by Django 5.0.6 on 2024-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_graduates_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='experience',
            field=models.CharField(choices=[('Год', 'Более 1 года'), ('От пяти лет', 'Более 5 лет'), ('От десяти лет', 'Более 15 лет')], max_length=50, verbose_name='Опыт'),
        ),
    ]
