# Generated by Django 5.0.6 on 2024-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_students_administrator_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='user',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='successes',
            field=models.TextField(blank=True),
        ),
    ]
