# Generated by Django 5.0.6 on 2024-07-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teachers_experience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Contacts',
        ),
    ]
