# Generated by Django 5.0.6 on 2024-06-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_teachers_user_alter_teachers_successes'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratortypes',
            name='choosing_ky',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='administratortypes',
            name='choosing_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appealtostudents',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appealtostudents',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appealtostudents',
            name='title_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appealtostudents',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='content_ky',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='content_ru',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ky',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graduates',
            name='name_ky',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='graduates',
            name='name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='graduates',
            name='sourname_ky',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='graduates',
            name='sourname_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourachievements',
            name='content_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourachievements',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='grade_ky',
            field=models.CharField(choices=[('fifth', '5'), ('sixth', '6'), ('seventh', '7'), ('eighth', '8'), ('ninth', '9'), ('tenth', '10'), ('eleventh', '11')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='grade_ru',
            field=models.CharField(choices=[('fifth', '5'), ('sixth', '6'), ('seventh', '7'), ('eighth', '8'), ('ninth', '9'), ('tenth', '10'), ('eleventh', '11')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='name_ky',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='name_of_grade_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nameofgrades'),
        ),
        migrations.AddField(
            model_name='students',
            name='name_of_grade_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nameofgrades'),
        ),
        migrations.AddField(
            model_name='students',
            name='name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='olympian_status_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia'),
        ),
        migrations.AddField(
            model_name='students',
            name='olympian_status_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia'),
        ),
        migrations.AddField(
            model_name='students',
            name='sourname_ky',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='sourname_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='successfulstudents',
            name='content_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successfulstudents',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='education_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='education_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name_ky',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject_ky',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='successes_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='successes_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='surname_ky',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='surname_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='title_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromgraduates',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='title_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thanksnotefromstudents',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
