# Generated by Django 5.0.6 on 2024-07-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_feedback_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='content_ky',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromgraduates',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromgraduates',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromgraduates',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromgraduates',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromstudents',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromstudents',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromstudents',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='thanksnotefromstudents',
            name='title_ru',
        ),
    ]
