# Generated by Django 5.0.6 on 2024-07-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gimnasiumclass_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
    ]
