# Generated by Django 5.0.6 on 2024-06-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_administratortypes_choosing_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduates',
            old_name='sourname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='sourname',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='administratortypes',
            name='choosing_ky',
        ),
        migrations.RemoveField(
            model_name='administratortypes',
            name='choosing_ru',
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='sourname_ky',
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='sourname_ru',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='students',
            name='sourname_ky',
        ),
        migrations.RemoveField(
            model_name='students',
            name='sourname_ru',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='surname_ky',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='surname_ru',
        ),
    ]
