# Generated by Django 5.0.6 on 2024-07-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
