# Generated by Django 5.0.6 on 2024-06-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_sourname_graduates_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='grade_ky',
        ),
        migrations.RemoveField(
            model_name='students',
            name='grade_ru',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name_of_grade_ky',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name_of_grade_ru',
        ),
        migrations.AddField(
            model_name='nameofgrades',
            name='choosing_ky',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nameofgrades',
            name='choosing_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
