# Generated by Django 5.0.6 on 2024-06-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_students_grade_ky_remove_students_grade_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Ученики/Окуучулар'},
        ),
    ]
