# Generated by Django 5.0.6 on 2024-07-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appealtostudents',
            options={'verbose_name': 'Обращение к ученикам (от выпускников)', 'verbose_name_plural': 'Обращение к ученикам (от выпускников)'},
        ),
        migrations.AlterModelOptions(
            name='nameofgrades',
            options={'verbose_name': 'Добавить имени класса', 'verbose_name_plural': 'Добавить имена классов'},
        ),
        migrations.AlterModelOptions(
            name='namesofolympia',
            options={'verbose_name': 'Добавить название олимпиады', 'verbose_name_plural': 'Добавить названия олимпиад'},
        ),
    ]
