# Generated by Django 5.0.6 on 2024-06-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratortypes',
            options={'verbose_name': 'Должности среди учащихся / Студенттер арасындагы позициялар', 'verbose_name_plural': 'Должности среди учащихся / Студенттер арасындагы позициялар'},
        ),
        migrations.AlterModelOptions(
            name='appealtostudents',
            options={'verbose_name': 'Обращение к ученикам / Окуучуларга бүтүрүүчүлөрдөн кайрылуу', 'verbose_name_plural': 'Обращение к ученикам / Окуучуларга бүтүрүүчүлөрдөн кайрылуу'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'Форум / Форум', 'verbose_name_plural': 'Форум / Форум'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея / Галерея', 'verbose_name_plural': 'Галерея / Галерея'},
        ),
        migrations.AlterModelOptions(
            name='graduates',
            options={'verbose_name': 'Выпускники / Бүтүрүүчүлөр', 'verbose_name_plural': 'Выпускники / Бүтүрүүчүлөр'},
        ),
        migrations.AlterModelOptions(
            name='nameofgrades',
            options={'verbose_name': 'Класстардын аталышы / Название классов', 'verbose_name_plural': 'Класстардын аталышы / Название классов'},
        ),
        migrations.AlterModelOptions(
            name='namesofolympia',
            options={'verbose_name': 'Название олимпиады / Олимпиаданын аталышы', 'verbose_name_plural': 'Название олимпиады / Олимпиаданын аталышы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости / Жаңылыктар', 'verbose_name_plural': 'Новости / Жаңылыктар'},
        ),
        migrations.AlterModelOptions(
            name='olympians',
            options={'verbose_name': 'Олимпийцы / Олимпиецтер', 'verbose_name_plural': 'Олимпийцы / Олимпиецтер'},
        ),
        migrations.AlterModelOptions(
            name='ourachievements',
            options={'verbose_name': 'Наши достижения / Биздин жетишкендиктерибиз', 'verbose_name_plural': 'Наши достижения / Биздин жетишкендиктер'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Ученики/Окуучулар', 'verbose_name_plural': 'Ученики/Окуучулар'},
        ),
        migrations.AlterModelOptions(
            name='successfulstudents',
            options={'verbose_name': 'Успешные выпускники / Ийгиликтүү бүтүрүүчүлөр', 'verbose_name_plural': 'Успешные выпускники / Ийгиликтүү бүтүрүүчүлөр'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учителя / Мугалимдер', 'verbose_name_plural': 'Учителя / Мугалимдер'},
        ),
        migrations.AlterModelOptions(
            name='thanksnotefromgraduates',
            options={'verbose_name': 'Благодарственное письмо / Ыраазычылык кат', 'verbose_name_plural': 'Благодарственное письмо / Ыраазычылык кат'},
        ),
        migrations.AlterModelOptions(
            name='thanksnotefromstudents',
            options={'verbose_name': 'Благодарственное письмо (от учеников) / Ыраазычылык кат (окуучулардан)', 'verbose_name_plural': 'Благодарственное письмо (от учеников) / Ыраазычылык кат (окуучулардан)'},
        ),
    ]
