# Generated by Django 5.0.6 on 2024-06-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_administratortypes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameofgrades',
            name='choosing',
            field=models.CharField(max_length=20, unique=True, verbose_name='Выбор'),
        ),
        migrations.AlterField(
            model_name='nameofgrades',
            name='choosing_ky',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Выбор'),
        ),
        migrations.AlterField(
            model_name='nameofgrades',
            name='choosing_ru',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Выбор'),
        ),
    ]
