# Generated by Django 5.0.6 on 2024-06-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_nameofgrades_choosing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameofgrades',
            name='choosing_ky',
        ),
        migrations.RemoveField(
            model_name='nameofgrades',
            name='choosing_ru',
        ),
    ]
