# Generated by Django 5.0.6 on 2024-06-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_nameofgrades_choosing_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratortypes',
            name='choosing',
            field=models.CharField(max_length=50, unique=True, verbose_name='Выбор/Тандоо'),
        ),
        migrations.AlterField(
            model_name='nameofgrades',
            name='choosing',
            field=models.CharField(max_length=20, unique=True, verbose_name='Выбор/Тандоо'),
        ),
        migrations.AlterField(
            model_name='namesofolympia',
            name='choosing',
            field=models.CharField(max_length=20, unique=True, verbose_name='Выбор/Тандоо'),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('fifth', '5'), ('sixth', '6'), ('seventh', '7'), ('eighth', '8'), ('ninth', '9'), ('tenth', '10'), ('eleventh', '11')], max_length=50, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя/Аты'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name_of_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nameofgrades', verbose_name='Название класса/Классынын аты'),
        ),
        migrations.AlterField(
            model_name='students',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
    ]
