# Generated by Django 5.0.6 on 2024-06-30 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_administratortypes_choosing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=1, upload_to='gallery/', verbose_name='Изображение/Сүрөт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки/Чыгаруу күнү'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания/Жаралуу күнү'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки/Чыгаруу күнү'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя/Аты'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки/Чыгаруу күнү'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год/Жылы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания/Жаралуу күнү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки/Чыгаруу күнү'),
        ),
        migrations.AlterField(
            model_name='olympians',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students', verbose_name='Окуучу'),
        ),
        migrations.AlterField(
            model_name='ourachievements',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='ourachievements',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='ourachievements',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='ourachievements',
            name='image',
            field=models.ImageField(upload_to='our_achievements/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='students',
            name='administrator_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.administratortypes', verbose_name='Позициясы'),
        ),
        migrations.AlterField(
            model_name='students',
            name='olympian_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпийц'),
        ),
        migrations.AlterField(
            model_name='students',
            name='olympian_status_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпийц'),
        ),
        migrations.AlterField(
            model_name='students',
            name='olympian_status_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпийц'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='image',
            field=models.ImageField(upload_to='successful_students/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки/Чыгаруу күнү'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='education',
            field=models.CharField(blank=True, max_length=200, verbose_name='Образование/Билими'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='education_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование/Билими'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='education_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование/Билими'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='experience',
            field=models.CharField(choices=[('Год', '1'), ('От пяти лет', '5+'), ('От десяти лет', '10+')], max_length=50, verbose_name='Опыт/Тажрыйбасы'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(upload_to='teachers_images/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя/Аты'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='Предмет/Сабак'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject_ky',
            field=models.CharField(max_length=20, null=True, verbose_name='Предмет/Сабак'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Предмет/Сабак'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='successes',
            field=models.TextField(blank=True, verbose_name='Успехи/Ийгиликтери'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='successes_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Успехи/Ийгиликтери'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='successes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Успехи/Ийгиликтери'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки/Чыгаруу күнү'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок/Кириш сөз'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки/Чыгаруу күнү'),
        ),
    ]
