# Generated by Django 5.0.6 on 2024-06-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_gallery_images_gallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
    ]
