# Generated by Django 5.0.6 on 2024-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_news_title_remove_news_title_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduates',
            name='content',
            field=models.TextField(default=1, verbose_name='Контент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduates',
            name='image',
            field=models.ImageField(default=1, upload_to='graduates/%Y/%m/%d/', verbose_name='Изображение/Сүрөт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='ourachievements',
            name='image',
            field=models.ImageField(upload_to='our_achievements/%Y/%m/%d/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='image',
            field=models.ImageField(upload_to='successful_students/%Y/%m/%d/', verbose_name='Изображение/Сүрөт'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(upload_to='teachers_images/%Y/%m/%d/', verbose_name='Изображение/Сүрөт'),
        ),
    ]
