# Generated by Django 5.0.6 on 2024-07-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_graduates_content_graduates_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympians',
            name='name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Olymp', to='main.students', verbose_name='Имя/Аты'),
            preserve_default=False,
        ),
    ]
