# Generated by Django 5.0.6 on 2024-07-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_olympians_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratortypes',
            options={'verbose_name': 'Должности среди учащихся', 'verbose_name_plural': 'Должности среди учащихся'},
        ),
        migrations.AlterModelOptions(
            name='appealtostudents',
            options={'verbose_name': 'Обращение к ученикам', 'verbose_name_plural': 'Обращение к ученикам'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'Форум', 'verbose_name_plural': 'Форум'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='graduates',
            options={'verbose_name': 'Выпускники', 'verbose_name_plural': 'Выпускники'},
        ),
        migrations.AlterModelOptions(
            name='nameofgrades',
            options={'verbose_name': 'Название классов', 'verbose_name_plural': 'Название классов'},
        ),
        migrations.AlterModelOptions(
            name='namesofolympia',
            options={'verbose_name': 'Название олимпиады', 'verbose_name_plural': 'Название олимпиады'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='olympians',
            options={'verbose_name': 'Олимпийцы', 'verbose_name_plural': 'Олимпийцы'},
        ),
        migrations.AlterModelOptions(
            name='ourachievements',
            options={'verbose_name': 'Наши достижения', 'verbose_name_plural': 'Наши достижения'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Ученики', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='successfulstudents',
            options={'verbose_name': 'Успешные выпускники', 'verbose_name_plural': 'Успешные выпускники'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='thanksnotefromgraduates',
            options={'verbose_name': 'Благодарственное письмо', 'verbose_name_plural': 'Благодарственное письмо'},
        ),
        migrations.AlterModelOptions(
            name='thanksnotefromstudents',
            options={'verbose_name': 'Благодарственное письмо (от учеников)', 'verbose_name_plural': 'Благодарственное письмо (от учеников)'},
        ),
        migrations.AlterField(
            model_name='administratortypes',
            name='choosing',
            field=models.CharField(max_length=50, unique=True, verbose_name='Выбор'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='appealtostudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='image',
            field=models.ImageField(upload_to='graduates/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='nameofgrades',
            name='choosing',
            field=models.CharField(max_length=20, unique=True, verbose_name='Выбор'),
        ),
        migrations.AlterField(
            model_name='namesofolympia',
            name='choosing',
            field=models.CharField(max_length=20, unique=True, verbose_name='Выбор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='olympians',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='ourachievements',
            name='image',
            field=models.ImageField(upload_to='our_achievements/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='students',
            name='administrator_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.administratortypes', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name_of_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nameofgrades', verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='students',
            name='olympian_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпиец'),
        ),
        migrations.AlterField(
            model_name='students',
            name='olympian_status_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпиец'),
        ),
        migrations.AlterField(
            model_name='students',
            name='olympian_status_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.namesofolympia', verbose_name='Олимпиец'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='image',
            field=models.ImageField(upload_to='successful_students/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='successfulstudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='education',
            field=models.CharField(blank=True, max_length=200, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='education_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='education_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='experience',
            field=models.CharField(choices=[('Год', '1'), ('От пяти лет', '5+'), ('От десяти лет', '10+')], max_length=50, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(upload_to='teachers_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject_ky',
            field=models.CharField(max_length=20, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='successes',
            field=models.TextField(blank=True, verbose_name='Успехи'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='successes_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Успехи'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='successes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Успехи'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromgraduates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='thanksnotefromstudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата загрузки'),
        ),
    ]
