# Generated by Django 5.0.6 on 2024-07-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_administratortypes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
    ]
