# Generated by Django 5.0.6 on 2024-07-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_students_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.PositiveIntegerField(null=True, unique=True, verbose_name='Контакты')),
                ('address', models.CharField(max_length=200, null=True, unique=True, verbose_name='Адрес')),
                ('social_links', models.URLField(blank=True, null=True, verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
