# Generated by Django 5.0.6 on 2024-07-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contacts',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер телефона(+996)'),
        ),
    ]
