# Generated by Django 5.0.6 on 2024-07-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_feedback_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='contacts',
            new_name='phone_number',
        ),
    ]
