# Generated by Django 5.0.6 on 2024-07-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_contacts_feedback_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='social_links',
        ),
        migrations.AddField(
            model_name='feedback',
            name='instagram',
            field=models.URLField(null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='telegram',
            field=models.URLField(null=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='youtube',
            field=models.URLField(null=True, verbose_name='Youtube'),
        ),
    ]
