# Generated by Django 5.0.6 on 2024-07-05 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_feedback_social_links_feedback_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарии к постам',
                'verbose_name_plural': 'Комментарии к постам',
            },
        ),
        migrations.CreateModel(
            name='SuccessfulGraduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='successful_graduates/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Успешные выпускники',
                'verbose_name_plural': 'Успешные выпускники',
            },
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='SuccessfulStudents',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.news', verbose_name='Связка с "Новости"'),
        ),
        migrations.AddField(
            model_name='comments',
            name='our_achievements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ourachievements', verbose_name='Связка с "Наши достижения"'),
        ),
        migrations.AddField(
            model_name='comments',
            name='successful_graduates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.successfulgraduates', verbose_name='Связка с "Успешные студенты"'),
        ),
    ]
